baseURL = "https://ssha.org/"
languageCode = "en-us"
title = "Social Science History Association"
contact = "executivedirector@ssha.org"
theme = "minimal"
canonifyURLs = true
publishDir = "build"

[params]
    author="Social Science History Association"
    description="Interdisciplinary perspectives on the past"
    accent="#006dc7"
    showBorder = false
    font="Zilla Slab"

[deployment]

[[deployment.targets]]
name = "ssha.org"
URL = "s3://aws-website-ssha-o06c3?region=us-east-1"

cloudFrontDistributionID =  "E1R2XXNL0UQGFN"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

## Main menu ##

[[menu.main]]
    url = "/"
    name = "Welcome"
    weight = 1

[[menu.main]]
    url = "/journal/"
    name = "SSH Journal"
    weight = 2

[[menu.main]]
    url = "/conference/"
    name = "Conference"
    weight = 3

[[menu.main]]
    url = "/networks/"
    name = "Networks"
    weight = 4

[[menu.main]]
    url = "/membership/"
    name = "Membership"
    weight = 5

[[menu.main]]
    url = "/prizes/"
    name = "Prizes"
    weight = 6

[[menu.main]]
    url = "/donate/"
    name = "Donate"
    weight = 7

[[menu.main]]
    url = "/news/"
    name = "News"
    weight = 8

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 9
